Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.define "app01" do |app|
    app.vm.box = "ubuntu/trusty64"
    app.vm.network "private_network", ip: "10.0.0.101"
    app.vm.network "forwarded_port", guest: 8080, host: 8101
  end

  config.vm.define "app02" do |app|
    app.vm.box = "ubuntu/trusty64"
    app.vm.network "private_network", ip: "10.0.0.102"
    app.vm.network "forwarded_port", guest: 8080, host: 8102
  end

  config.vm.define "monitoring" do |monitoring|
    monitoring.vm.box = "ubuntu/trusty64"
    monitoring.vm.network "private_network", ip: "10.0.0.200"
  end
end